### PR TITLE
Fix check for externalauth in login block

### LINKED ISSUE #466: Missing dependency on externalauth in indieweb_indieauth
The auth module makes use of functionality in the [externauth](https://drupal.org/project/externalauth) module, but it does not list it as a dependency, which means an exception will be thrown when the authentication block is added to a site.

### PR DESCRIPTION
**Pull request by eelkeblok**
This fixes #466. Was happy to find the config form basically did exactly what I wanted to add :)

It also adds some proper dependecy injection to the components involved and removes the logic from the block itself; it just replicated logic that was already in the form too.

### CODE REVIEW

**Comment by swentel** [comment]
This still crashes when:

- the block is placed
- you're authenticated
- and external authentication is not enabled

I placed the block on any page, and as user 1, I get this exception: Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "externalauth.authmap". in Drupal\Component\DependencyInjection\Container->get() (line 153 of /home/drupal/realize.be/core/lib/Drupal/Component/DependencyInjection/Container.php).

So I guess that still needs a fix :)

**Comment by eelkeblok** [comment]
Hmm. Interesting. Good catch. I guess I need to explicitly initialise the member variable as NULL, then.

**Comment by eelkeblok** [comment]
Which version of PHP are you running on? I can't reproduce this ATM, but my test environment is on PHP 7.0 because my personal site is too.

**Comment by eelkeblok** [comment]
Actually, scratch most of the above. That is just really strange, because before requesting the service at line 157 of IndieAuthLoginForm, I am checking if the container has it at all at line 156. Can you see where the service is being requested in your error case?

**Comment by swentel** [comment]
I'm running PHP 7.2.24 at the moment, but I don't think that would cause the exception, I'll have a look at it this evening normally.

**Comment by eelkeblok** [comment]
I've updated the other location where the service was being requested without checking for its existence. I hope that addresses the situation you found.

**Comment by swentel** [comment]
Hmm, I'm starting to wonder whether I cleanly applied the patch, sorry about that :/
(when I did git apply now again it simply didn't made the changes, crap)

Anyway, this does fix the problem, so great!

**Pull request merged**
